services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: entrarolereaper-server:local
    environment:
      ROLE_REAPER_RESET_DB: "1"
      ASPNETCORE_ENVIRONMENT: "Production"
      AzureAd__Instance: "https://login.microsoftonline.com/"
      AzureAd__TenantId: "${AZUREAD_TENANT_ID}"
      AzureAd__ClientId: "${AZUREAD_CLIENT_ID}"
      AzureAd__ClientSecret: "${AZUREAD_CLIENT_SECRET}"
      AzureAd__Audience: "${AZUREAD_AUDIENCE}"
      AzureAd__Domain: "${AZUREAD_DOMAIN}"
      Cors__AllowedOrigins__0: "http://localhost:5173"
      Cache__SqlitePath: "/cache/rolereaper_cache.sqlite"
    expose:
      - "8080"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev
    volumes:
      - /Users/frode.hus/rolereaper:/cache
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        VITE_AAD_TENANT_ID: ${AZUREAD_TENANT_ID}
        VITE_AAD_CLIENT_ID: ${AZUREAD_CLIENT_ID}
        VITE_API_SCOPE: ${VITE_API_SCOPE}
        VITE_API_URL: http://localhost:5173
    image: entrarolereaper-web:local
    depends_on:
      - server
    ports:
      - "5173:8080"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev
    networks:
      - appnet

networks:
  appnet: {}

volumes:
  rolereaper-cache: {}
    

