// <auto-generated />
using System;
using EntraRoleReaper.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ReaperDbContext))]
    [Migration("20250820081547_v0.2")]
    partial class v02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("ActivityPropertyResourceAction", b =>
                {
                    b.Property<Guid>("MappedActivityPropertiesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MappedResourceActionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("MappedActivityPropertiesId", "MappedResourceActionsId");

                    b.HasIndex("MappedResourceActionsId");

                    b.ToTable("ActivityPropertyResourceAction");
                });

            modelBuilder.Entity("ActivityResourceAction", b =>
                {
                    b.Property<Guid>("MappedActivitiesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MappedResourceActionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("MappedActivitiesId", "MappedResourceActionsId");

                    b.HasIndex("MappedResourceActionsId");

                    b.ToTable("ActivityResourceAction");
                });

            modelBuilder.Entity("EntraRoleReaper.Api.Data.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditCategory")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("EntraRoleReaper.Api.Data.Models.ActivityProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityProperties");
                });

            modelBuilder.Entity("EntraRoleReaper.Api.Data.Models.PermissionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivileged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleDefinitionId");

                    b.ToTable("PermissionSets");
                });

            modelBuilder.Entity("EntraRoleReaper.Api.Data.Models.ResourceAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivileged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .IsUnique();

                    b.ToTable("ResourceActions");
                });

            modelBuilder.Entity("EntraRoleReaper.Api.Data.Models.RoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id", "DisplayName")
                        .IsUnique();

                    b.ToTable("RoleDefinitions");
                });

            modelBuilder.Entity("EntraRoleReaper.Api.Data.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantDomain")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PermissionSetResourceAction", b =>
                {
                    b.Property<Guid>("PermissionSetsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceActionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("PermissionSetsId", "ResourceActionsId");

                    b.HasIndex("ResourceActionsId");

                    b.ToTable("PermissionSetResourceAction");
                });

            modelBuilder.Entity("ActivityPropertyResourceAction", b =>
                {
                    b.HasOne("EntraRoleReaper.Api.Data.Models.ActivityProperty", null)
                        .WithMany()
                        .HasForeignKey("MappedActivityPropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntraRoleReaper.Api.Data.Models.ResourceAction", null)
                        .WithMany()
                        .HasForeignKey("MappedResourceActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActivityResourceAction", b =>
                {
                    b.HasOne("EntraRoleReaper.Api.Data.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("MappedActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntraRoleReaper.Api.Data.Models.ResourceAction", null)
                        .WithMany()
                        .HasForeignKey("MappedResourceActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntraRoleReaper.Api.Data.Models.ActivityProperty", b =>
                {
                    b.HasOne("EntraRoleReaper.Api.Data.Models.Activity", null)
                        .WithMany("Properties")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntraRoleReaper.Api.Data.Models.PermissionSet", b =>
                {
                    b.HasOne("EntraRoleReaper.Api.Data.Models.RoleDefinition", null)
                        .WithMany("PermissionSets")
                        .HasForeignKey("RoleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionSetResourceAction", b =>
                {
                    b.HasOne("EntraRoleReaper.Api.Data.Models.PermissionSet", null)
                        .WithMany()
                        .HasForeignKey("PermissionSetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntraRoleReaper.Api.Data.Models.ResourceAction", null)
                        .WithMany()
                        .HasForeignKey("ResourceActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntraRoleReaper.Api.Data.Models.Activity", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("EntraRoleReaper.Api.Data.Models.RoleDefinition", b =>
                {
                    b.Navigation("PermissionSets");
                });
#pragma warning restore 612, 618
        }
    }
}
